/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Knight2.glb --transform 
Files: Knight2.glb [37.54MB] > C:\Users\vanki\OneDrive\Desktop\cs105.021\src\loaders\HollowKnight\Knight2-transformed.glb [1.3MB] (97%)
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Knight2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/HollowKnight/Knight2-transformed.glb')
  const { actions, mixer } = useAnimations(animations, group)
  console.log(actions);

  useEffect(() => {
    actions?.walk.play();
  }, [actions, mixer]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig">
          <primitive object={nodes.spine} />
        </group>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.another} />
        <group name="Cube" position={[0, 1.532, 0]} scale={0.609}>
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Head} />
          <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials.Hitam} />
        </group>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.sword} position={[-0.17, 0.906, -0.364]} rotation={[0, 0, 0.849]} scale={[0.126, 0.126, 0.04]} />
        <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Hitam} skeleton={nodes.Cube001.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/HollowKnight/Knight2-transformed.glb')
