/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Knight2.glb --transform 
Files: Knight2.glb [37.54MB] > C:\Users\vanki\OneDrive\Desktop\cs105.021\src\loaders\HollowKnight\Knight2-transformed.glb [1.3MB] (97%)
*/

import { useState, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Knight2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/HollowKnight/Knight2-transformed.glb')
  const { actions, names, mixer } = useAnimations(animations, group)

  const [isWalking, setIsWalking] = useState(false);
  // console.log(actions);
  
  useFrame(() => {
    if (isWalking) {
      actions.walk.play();
    }
    else {
      actions.walk.stop();
    }
  })

  const handleKeyPress = (event) => {
    switch (event.keyCode) {
      case 87: //w
        setIsWalking(true);
        
        break;
      case 65: //a
        setIsWalking(true);

        break
      case 83: //s
        setIsWalking(true);
        
        break;
      case 68: // d
        setIsWalking(true);
        
        break;
    }
  }
  const handleKeyUp = (event) => {
    switch (event.keyCode) {
      case 87: //w
        setIsWalking(false);
        
        break;
      case 65: //a
        setIsWalking(false);

        break
      case 83: //s
        setIsWalking(false);
        
        break;
      case 68: // d
        setIsWalking(false);
        
        break;
    }
  }

  useEffect(() => {
    document.addEventListener("keydown", handleKeyPress);
    document.addEventListener("keyup", handleKeyUp);
    return () => {
      document.removeEventListener("keydown", handleKeyPress);
      document.removeEventListener("keyup", handleKeyUp);
    };
  });

  useEffect(() => {
    if (isWalking) {
      actions?.walk.play();
    }
  }, [actions, mixer, isWalking]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig">
          <primitive object={nodes.spine} />
        </group>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.another} />
        <group name="Cube" position={[0, 1.532, 0]} scale={0.609}>
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Head} />
          <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials.Hitam} />
        </group>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.sword} position={[-0.17, 0.906, -0.364]} rotation={[0, 0, 0.849]} scale={[0.126, 0.126, 0.04]} />
        <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Hitam} skeleton={nodes.Cube001.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/HollowKnight/Knight2-transformed.glb')
