/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf -T -o Husk.jsx 
Files: scene.gltf [37.27KB] > G:\vs_code\cs105\cs105-final\public\models\husk\scene-transformed.glb [655.09KB] (-1658%)
Author: Brandon Ehrman (https://sketchfab.com/NyxNoire)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hollow-knight-67-gorgeous-husk-b4657a09a53d404badd2f9dc85c98386
Title: Hollow Knight #67 - Gorgeous Husk
*/
import { useGLTF } from '@react-three/drei'

export default function Husk(props) {
  const { nodes, materials } = useGLTF('./models/husk/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0, -0.253, -0.204]} scale={[2.458, 2.437, 2.476]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial002} position={[0.695, -0.082, -1.648]} rotation={[0, -0.409, 0]} scale={0.183} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial003} position={[0.033, 1.006, -0.231]} rotation={[-0.045, -0.141, -0.031]} scale={[0.546, 0.651, 0.431]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial004} position={[-0.248, 1.368, -0.046]} rotation={[0.002, -0.141, 0.015]} scale={0.028} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.PaletteMaterial005} position={[-0.058, 1.147, 0.194]} rotation={[-0.389, -0.218, -0.001]} scale={[0.124, 0.172, 0.054]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.PaletteMaterial006} position={[0.033, 1.006, -0.231]} rotation={[-0.045, -0.141, -0.031]} scale={[0.546, 0.651, 0.431]} />
    </group>
  )
}

useGLTF.preload('./models/husk/scene-transformed.glb')
